### PR TITLE
Fix escape sequences in makefiles

### PR DESCRIPTION
**Pull request by nick87720z**
Not sure, how they usually do it in makefiles.

### CODE REVIEW

**Comment by brummer10** [comment]
which terminal do you use that this is needed? I mean here it works as it is. (bash)
True, it works with your patch as well, so I like to know for which environment it fix it.

**Comment by nick87720z** [comment]
It's unlikely to be terminal, it's rather echo/print command implementation (i.e. shell).
echo is not in posix shell standard, so its behavrior may differ, unike printf. I have gnu bash, which interprets encoded (not raw) esc sequences only with -e option. While printf always interprets them in first argument. I went simpler way by just turning this esc strings into raw form, which would pass any text utility as well (e.g. cat, tail, etc).

**Comment by nick87720z** [comment]
To add - I spent some time, writing some shell scripts for desktop (mainly tint2 executers), and tried to ensure they are portable by testing with dash shell. There I learned to use printf, moreover it's recommended. Of course, dash also supports echo, but there are no behavior arguments at all.
At least I would suggest to avoid non-posix features in makefiles.
Update: Oh, I see you mentioned you use bash. But as I said above, for me esc sequences are not interpreted without -e option. :/

**Comment by brummer10** [comment]
Okay, thanks you. Makes sense. merged

**Pull request merged**
